language: node_js
node_js:
  - 16

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version
  # Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  # Tagging
  - docker tag udagram-api-feed trandat2008/udagram-api-feed:v1
  - docker tag udagram-api-user trandat2008/udagram-api-user:v1
  - docker tag udagram-frontend trandat2008/udagram-frontend:v1
  - docker tag udagram-reverseproxy trandat2008/udagram-reverseproxy:v1
  # Push
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push trandat2008/udagram-api-feed:v1
  - docker push trandat2008/udagram-api-user:v1
  - docker push trandat2008/udagram-frontend:v1
  - docker push trandat2008/udagram-reverseproxy:v1
