language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version
  # Build
  - docker build -f udagram-api-feed/Dockerfile -t udagram-api-feed ./udagram-api-feed
  - docker build -f udagram-api-user/Dockerfile -t udagram-api-user ./udagram-api-user
  - docker build -f udagram-frontend/Dockerfile -t udagram-frontend ./udagram-frontend
  - docker build -f udagram-reverseproxy/Dockerfile -t udagram-reverseproxy ./udagram-reverseproxy
  # Tagging
  - docker tag udagram-api-feed trandat2008/udagram-api-feed:v2
  - docker tag udagram-api-user trandat2008/udagram-api-user:v2
  - docker tag udagram-frontend trandat2008/udagram-frontend:v2
  - docker tag udagram-reverseproxy trandat2008/udagram-reverseproxy:v2
  # Push
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push trandat2008/udagram-api-feed:v2
  - docker push trandat2008/udagram-api-user:v2
  - docker push trandat2008/udagram-frontend:v2
  - docker push trandat2008/udagram-reverseproxy:v2
