apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      run: frontend
  template:
    metadata:
      labels:
        run: frontend
    spec:
      containers:
      - name: frontend
        image: docker.io/trandat2008/udagram-frontend:v1
        ports:
        - containerPort: 80
        resources:
          limits: 
            cpu: 500m
          requests:
            cpu: 250m